### ISSUE TITLE
Narrative ontology prefix

### ISSUE THREAD

**Issue by marilenadaquino** [spice-h2020/SON#44]
@alieto Change prefixes in the ontology whenever creating new entities / properties
https://github.com/spice-h2020/SON/blob/main/Narrative-Labyrinth/ontology.owl

e.g. https://w3id.org/spice/SON/hasCharacter -> https://w3id.org/spice/SON/Narrative-Labyrinth#hasCharacter

**Comment by alieto** [comment]
@marilenadaquino done, thanks https://github.com/spice-h2020/SON/blob/main/Narrative-Labyrinth/ontology.owl

**Comment by marilenadaquino** [comment]
There are still some prefixes to be fixed, e.g. https://w3id.org/spice/SON/List -> https://w3id.org/spice/SON/onto-prefix/List

**Comment by alieto** [comment]
@marilenadaquino now it should be corrected. I have uploaded the last version here: https://github.com/spice-h2020/SON/blob/main/Narrative-Labyrinth/ontology.owl

**Comment by marilenadaquino** [comment]
Oki doki! misread :) let's close it
